---

- hosts: localhost
  become: true
  tasks:

  - name: download the latest version of Docker Compose
    shell: sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

  - name: Apply executable permissions to the binary
    shell: sudo chmod +x /usr/local/bin/docker-compose

